emotion_tracker/urls.py
from django.urls import path
from . import views

app_name = 'emotion_tracker'
urlpatterns = [
    path('', views.index, name='index'),
    path("upload/", views.upload, name="upload"),
    path("detail/<str:video_id>/", views.detail, name="detail"),
    path('upload/download_video/', views.download_video, name='download_video'),
    path('upload/frames/<str:filename>/', views.serve_frame, name='serve_frame'),
]

est_final/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("polls/", include("polls.urls")),
    path("emotion_tracker/", include("emotion_tracker.urls")),
    path('admin/', admin.site.urls)
]
# 미디어 파일 서빙 설정
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

emotion_tracker/models.py
import os
from django.db import models
from django.conf import settings

class YouTubeVideo(models.Model):
    video_id = models.CharField(max_length=50, unique=True)
    video_url = models.URLField()
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    description = models.TextField()
    thumbnail_url = models.URLField()
    channel_url = models.URLField()
    duration = models.IntegerField(default=0)

    happy = models.IntegerField(default=0)
    anger = models.IntegerField(default=0)
    sadness = models.IntegerField(default=0)
    panic = models.IntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    actions = ['delete_selected']  # 여러 항목을 한 번에 삭제하는 기능 활성화

    def __str__(self):
        return f'{self.title} / {self.author} / {self.description}'
    def delete(self, *args, **kwargs):
        # 관련된 모든 FrameDetection 객체의 파일 삭제
        for frame_detection in self.framedetection_set.all():
            if frame_detection.frame_filename:
                if os.path.isfile(frame_detection.frame_filename.path):
                    os.remove(frame_detection.frame_filename.path)
        # YouTubeVideo 객체 삭제
        super().delete(*args, **kwargs)


class FrameDetection(models.Model):
    video = models.ForeignKey(YouTubeVideo, on_delete=models.CASCADE)
    frame_number = models.IntegerField()
    confidence = models.FloatField(null=True, blank=True)
    detection_class = models.IntegerField(null=True, blank=True)
    frame_filename = models.FileField(upload_to='')

    def __str__(self):
        return f'{self.frame_number} / {self.confidence} / {self.detection_class}'
    
    def delete(self, *args, **kwargs):
        # 파일이 존재하면 삭제
        if self.frame_filename:
            if os.path.isfile(self.frame_filename.path):
                os.remove(self.frame_filename.path)
        super().delete(*args, **kwargs)

emotion_tracker/views.py
from django.shortcuts import render
import os
from pytubefix import YouTube
from django.http import JsonResponse, FileResponse, StreamingHttpResponse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import cv2
import json
from ultralytics import YOLO
from django.db import transaction
from .models import YouTubeVideo, FrameDetection
from .utils import get_top_comments, format_duration
from django.db.models import Q
import logging

logger = logging.getLogger(__name__)

def index(request):
    
    search = request.GET.get('search', None)  # 검색어 가져오기
    keyword = request.GET.get('keyword', None)  # 검색어 가져오기
    if search:
        # YouTubeVideo 모델에서 데이터를 조회
        emotions = search.split(',')
        videos = YouTubeVideo.objects.filter(
            Q(
                Q(happy__gte=emotions[0]) &
                Q(anger__gte=emotions[1]) &
                Q(sadness__gte=emotions[2]) &
                Q(panic__gte=emotions[3])
            )|
            (Q(title__icontains=keyword))
        ).order_by('-created_at')
    else:
        # YouTubeVideo 모델에서 데이터를 조회
        videos = YouTubeVideo.objects.all().order_by('-created_at')
    
    
    # 데이터를 딕셔너리 형식으로 변환하여 템플릿에 전달
    video_data = [
        {
            "title": video.title,
            "author": video.author,
            "description": video.description,
            "thumbnail_url": video.thumbnail_url,
            "channel_url": video.channel_url,  # 또는 다른 비디오 관련 URL
            "url": video.video_url,  # 또는 다른 비디오 관련 URL
            "happy": video.happy,
            "anger": video.anger,
            "sadness": video.sadness,
            "panic": video.panic,
            "video_id": video.video_id,
            "duration": format_duration(video.duration)
        }
        for video in videos
    ]
    return render(request, "emotion_tracker/index.html", {"videos": video_data})


def upload(request):
    
    return render(request, "emotion_tracker/upload.html")


def detail(request, video_id):
    video = YouTubeVideo.objects.get(video_id=video_id)
    frames = FrameDetection.objects.filter(video=video)

    data = [{
            'frame_number': frame.frame_number,
            'confidence': frame.confidence,
            'detection_class': frame.detection_class,
            'frame_filename': frame.frame_filename.url,
        } for frame in frames]
    

    # 댓글 가져오기
    comments = get_top_comments(video_id, max_comments=5)

    return render(request, "emotion_tracker/detail.html", {
        "video": video,
        "frames": json.dumps(data),  # Send JSON as a string
        "comments": json.dumps(comments),
        "duration": format_duration(video.duration)
    })

# Frames 저장 경로 설정
# FRAME_DIR = os.path.join(settings.MEDIA_ROOT, 'frames')
FRAME_DIR = settings.MEDIA_ROOT

os.makedirs(FRAME_DIR, exist_ok=True)

@csrf_exempt
def download_video(request):
    if request.method == 'POST':
        try:
            def process_frames():
                data = json.loads(request.body)
                youtube_url = data.get('youtube_url')
                
                # YouTube 영상 다운로드
                yt = YouTube(youtube_url)
                stream = yt.streams.filter(progressive=True, file_extension='mp4').first()
                temp_video_path = os.path.join(settings.MEDIA_ROOT, f"{yt.video_id}.mp4")
                stream.download(output_path=settings.MEDIA_ROOT, filename=temp_video_path)

                # yt.video_id = 'NbOQWjqf6QU'
                # yt.thumbnail_url = 'https://i.ytimg.com/vi/NbOQWjqf6QU/sddefault.jpg?sqp=-oaymwEoCIAFEOAD8quKqQMcGADwAQH4AbYIgAKAD4oCDAgAEAEYciBXKEAwDw==&rs=AOn4CLBo5jdTkLCc3ScSWvxl_MF8PeBSCQ'
                # yt.title = '점점 커지는 음식 먹기 #도레미챌린지'
                # yt.author = '일오팔'
                # yt.channel_url = 'https://www.youtube.com/channel/UCJ4ETdbjB1MDhjwEZDtUlBQ'
                # yt.description = '@bomulsum_g'
                
                # Create or get the video instance
                video, created = YouTubeVideo.objects.get_or_create(
                    video_id=yt.video_id,
                    defaults={
                        'title': yt.title,
                        'author': yt.author,
                        'description': yt.description,
                        'thumbnail_url': yt.thumbnail_url,
                        'channel_url': yt.channel_url,
                        'video_url': youtube_url,
                        'duration' : yt.length,
                    }
                )
                if created == False:
                    error_response = {'error': f'이미 등록된 영상입니다.'}
                    yield json.dumps(error_response)
                    return StreamingHttpResponse(process_frames(), content_type='application/json')
                
                # video_id 에 대한
                # video_id = 'NbOQWjqf6QU'
                # frame 숫자 = 1
                # confidence = 0.53
                # class = 4
                # frame_filename = 


                # 모델 호출
                model = YOLO(os.path.join(settings.BASE_DIR, 'best.pt'))
                
                # 프레임 추출
                cap = cv2.VideoCapture(temp_video_path)
                frame_rate = int(cap.get(cv2.CAP_PROP_FPS))
                progress = 0
                frame_count = 0
                frame_num = 0
                total = 0
                detection_results = []
                emotions = [0] * 4

                with transaction.atomic():  # Using atomic transaction for bulk create
                    detections_to_create = []

                    while cap.isOpened():
                        ret, frame = cap.read()
                        if not ret:
                            break

                        # 1초마다 프레임 저장
                        if frame_count % frame_rate == 0:
                            frame_num += 1
                            frame_filename = f"{yt.video_id}_{frame_num}.jpg"
                            frame_path = os.path.join(FRAME_DIR, frame_filename)
                            
                            results = model.predict(frame)
                            # results = model.track(source=frame, persist=True)
                            results[0].save(frame_path)

                            # frame_paths.append(frame_filename)

                            progress = int((frame_count/ frame_rate / yt.length) * 100)
                            yield json.dumps({'progress': progress, 'frame': frame_filename}) + '\n'

                            # 결과에서 감지 정보 추출
                            detections = []
                            for box in results[0].boxes:
                                detections.append({
                                    'class': int(box.cls),
                                    'confidence': float(box.conf),
                                    'coordinates': box.xyxy.tolist()[0]  # [x1, y1, x2, y2]
                                })

                                # Add detections for the frame
                                detection_obj = FrameDetection(
                                    video=video,
                                    frame_number=frame_num,
                                    confidence=float(box.conf),
                                    detection_class=int(box.cls),
                                    frame_filename=frame_filename
                                )
                                detections_to_create.append(detection_obj)

                                # calculate emotion
                                total += 1
                                emotions[int(box.cls)] += float(box.conf)


                            
                            if len(results[0].boxes) == 0:
                                # Add detections for the frame
                                detection_obj = FrameDetection(
                                    video=video,
                                    frame_number=frame_num,
                                    confidence=-1,
                                    detection_class=-1,
                                    frame_filename=frame_filename
                                )
                                detections_to_create.append(detection_obj)


                            detection_results.append({
                                'frame': frame_filename,
                                'detections': detections
                            })
                                

                        frame_count += 1
                    yield json.dumps({'progress': 100, 'results': yt.video_id}) + '\n'

                total_emotion = 0
                for emotion in emotions:
                    total_emotion += emotion
                YouTubeVideo.objects.filter(video_id=yt.video_id).update(
                    happy=int(emotions[0]/total_emotion*10),
                    anger=int(emotions[1]/total_emotion*10),
                    sadness=int(emotions[2]/total_emotion*10),
                    panic=int(emotions[3]/total_emotion*10)
                )                
                # Bulk create detections
                FrameDetection.objects.bulk_create(detections_to_create)    

                cap.release()
                os.remove(temp_video_path)

            return StreamingHttpResponse(process_frames(), content_type='application/json')

        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)

    return JsonResponse({'error': 'Invalid request method!'}, status=405)


def serve_frame(request, filename):
    file_path = os.path.join(FRAME_DIR, filename)
    if os.path.exists(file_path):
        return FileResponse(open(file_path, 'rb'), content_type='image/jpeg')
    return JsonResponse({'error': 'File not found!'}, status=404)

emotion_tracker/templates/emotion_tracker/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video List</title>
    <!-- Materialize CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <style>
        .video-thumbnail {
            width: 100%;
            height: auto;
            object-fit: cover; /* 이미지 비율을 유지하면서 자르기 */
            height: 180px; /* 고정된 높이로 맞추기 */
        }

        .video-item {
            margin-bottom: 20px;
        }

        .video-title {
            font-size: 1.2rem;
            font-weight: bold;
            color: #333;
            margin-bottom: 10px;
            line-height: 1.2em;
            height: 3em; /* 일정한 높이 유지 */
            overflow: hidden;
            text-overflow: ellipsis;
        }

        /* video-description-div 스타일 */
        .video-description-div {
            background-color: #f0f0f0; /* 회색 배경 */
            padding: 10px 24px;             /* 패딩 추가 */
            margin-top: 10px;          /* 카드 본문과 간격 추가 */
            border-radius: 5px;       /* 모서리 둥글게 */
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1); /* 살짝 그림자 효과 */
            position: relative;       /* 다른 요소에 영향을 주지 않도록 */
            z-index: 2;               /* 다른 요소 위에 위치하게 */
        }

        /* video-description 링크 스타일 */
        .video-description-div .video-description a {
            text-decoration: none;    /* 링크 밑줄 제거 */
            color: #333;              /* 어두운 회색 텍스트 */
            font-weight: bold;        /* 텍스트 두껍게 */
        }

        .video-description-div .video-description a:hover {
            color: #007BFF;           /* 호버 시 색상 변경 */
        }

        /* video-description-div의 여백 효과 */
        .video-description-div::after {
            content: ""; /* 추가적인 구분선 스타일을 위한 가상 요소 */
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 3px;
            background: #ccc; /* 상단 경계선 */
            border-radius: 5px 5px 0 0;
        }

        .card {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            height: 100%;
            min-height: 300px; /* 최소 카드 높이 지정 */
        }


        .card .card-content {
            padding: 24px;
            border-radius: 0 0 2px 2px;
            padding: 24px 24px 0px 24px;
        }

        .search-bar-container {
            padding: 20px 20px 5px 20px;
            background-color: #f2f2f2;
            border-bottom: 1px solid #ddd;
        }

        .search-bar {
            width: 100%;
        }

        .search-row {
            display: flex;
            align-items: center;
            gap: 10px; /* 버튼과 검색바 사이의 간격 */
        }

        .search-button {
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .new-video-btn {
            display: flex;
            align-items: center;
        }

        .new-video-btn i {
            margin-right: 5px;
        }

        @media (max-width: 600px) {
            .new-video-btn {
                justify-content: center;
            }
        }

        .card .card-image img {
            display: block;
            border-radius: 5px 5px 0 0;
            position: relative;
            left: 0;
            right: 0;
            top: 0;
            bottom: 0;
            width: 100%;
        }

        /* 화살표 아이콘 스타일 */
        .arrow-icon {
            font-size: 16px;          /* 화살표 크기 */
            margin-left: 10px;        /* 화살표와 텍스트 사이 간격 */
            color: #007BFF;           /* 화살표 색상 */
        }

        /* 화살표 아이콘 호버 시 색상 변경 */
        .video-description-div .video-description a:hover .arrow-icon {
            color: #0056b3;           /* 호버 시 화살표 색상 */
        }

        .no-results-container {
            text-align: center;
            padding: 50px 20px;
            margin-top: 50px;
        }

        .no-results-image {
            width: 150px;
            height: 150px;
            margin-bottom: 20px;
        }

        .no-results-title {
            font-size: 24px;
            font-weight: bold;
            color: #333;
        }

        .no-results-text {
            font-size: 16px;
            color: #666;
            margin-bottom: 20px;
        }

        .no-results-button {
            padding: 10px 20px;
            font-size: 16px;
            color: white;
            background-color: #007BFF;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s;
        }

        .no-results-button:hover {
            background-color: #0056b3;
        }

        
    </style>
</head>
<body>
    <nav>
        <div class="nav-wrapper blue">
            <a href="{% url 'emotion_tracker:index' %}" class="brand-logo center">EmoTube</a>
            <ul id="nav-mobile" class="left">
                <li>
                    <a href="#!" class="new-video-btn" id="toggle-search">
                        <i class="material-icons left"></i>
                    </a>
                </li>
            </ul>
            <ul id="nav-mobile" class="right">
                <li>
                    <a href="{% url 'emotion_tracker:upload' %}" class="new-video-btn">
                        <i class="material-icons left">New</i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <!-- Search Bar -->
    <div class="search-bar-container" id="search-bar-container">
        <div class="row">
            <div class="col s12 search-row valign-wrapper">
                <input type="text" id="search-bar" class="search-bar" placeholder="영상 제목 또는 감정으로 검색...">
                <button class="btn blue waves-effect waves-light search-button" id="search-button">
                    <i class="material-icons">Search</i>
                </button>
            </div>
        </div>
    </div>

    <div class="container">
        <!-- <h4 class="center-align">Recommended Videos</h4> -->
        <div class="row" id="video-list">
            <!-- Loop through videos -->
            {% for video in videos %}
            <div class="col s12 m6 l4 video-item">
                <div class="card">
                    <div class="card-image">
                        <a href="{{ video.url }}" target="_blank">
                            <img src="{{ video.thumbnail_url }}" alt="Video Thumbnail" class="video-thumbnail">
                        </a> 
                        <!-- 시간 표시 -->
                        <div class="time-label" style="position: absolute; bottom: 8px; right: 8px; background: rgba(0, 0, 0, 0.7); color: white; padding: 3px 6px; border-radius: 4px; font-size: 12px;">
                            {{ video.duration }}
                        </div>
                    </div>
                    <div class="card-content">
                        <p class="video-title">
                            <a href="{{ video.url }}" target="_blank">{{ video.title|truncatewords:4 }}</a>
                        </p>
                        <p class="video-description">
                            <a href="{{ video.channel_url }}" target="_blank">{{ video.author }}</a>
                        </p>
                    </div>
                    <div class="video-description-div">
                        <p class="video-description">
                            <a href="{% url 'emotion_tracker:detail' video_id=video.video_id %}">
                                기쁨 {{ video.happy }}점 | 분노 {{ video.anger }}점 | 슬픔 {{ video.sadness }}점 | 당황 {{ video.panic }}점
                                <span class="arrow-icon">&#8594;</span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="no-results-container">
                <h2 class="no-results-title">검색 결과가 없습니다.</h2>
                <p class="no-results-text">다른 키워드로 검색해 보세요.</p>
                <a href="{% url 'emotion_tracker:index' %}" class="no-results-button">홈으로 돌아가기</a>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- Materialize JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        // 검색 필터링 기능
        const searchBarContainer = document.getElementById('search-bar-container');
        const searchBar = document.getElementById('search-bar');
        const searchButton = document.getElementById('search-button');
        const toggleSearch = document.getElementById('toggle-search');
        const videoList = document.getElementById('video-list');
        const videoItems = videoList.querySelectorAll('.video-item');

        toggleSearch.addEventListener('click', () => {
            if (searchBarContainer.style.display === 'block') {
                searchBarContainer.style.display = 'none'; // 검색바 숨기기
            } else {
                searchBarContainer.style.display = 'block'; // 검색바 표시
                searchBar.focus(); // 포커스 설정
            }
        });  


        // 검색 도움글 배열 (placeholder에 표시될 텍스트)
        const placeholders = [
            "오늘은 행복한 영화가 보고싶어...",
            "슬픈일이 있었어...",
            "영상 제목 또는 감정으로 검색..."
        ];

        let placeholderIndex = 0;

        // placeholder를 주기적으로 변경하는 함수
        function changePlaceholder() {
            const searchBar = document.getElementById('search-bar');
            searchBar.placeholder = placeholders[placeholderIndex];
            placeholderIndex = (placeholderIndex + 1) % placeholders.length; // 3개 도움글을 순차적으로 보여줌
        }

        // 페이지 로드 시 3초마다 placeholder 변경
        setInterval(changePlaceholder, 3000); // 3초마다 placeholder 변경


        //search button click
        searchButton.addEventListener('click', async () => {
            const apiKey = "AIzaSyBOSSGyQnVIG8uR746dfGKxbPTv3vmLdSA"; // Replace with your API key
            const apiUrl = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${apiKey}`;

            // Get the user input from the textarea
            let prompt = searchBar.value;
            if (!prompt) {
                alert("검색어를 입력해주세요!");
                return;
            }
            
            prompt = `검색어를 분석해서 우리 영상으로 사용자의 감정을 개선하려고 해,
            영상의 감성 수치를 다음과 같은 숫자(0~3), 숫자(0~3), 숫자(0~3), 숫자(0~3) 형식으로
            각각 행복,슬픔,놀람,화남으로 나타내줘 그리고 절대적으로 숫자 결과만 나타내줘, 
            검색어는 다음과 같아, ` + prompt;

            // Construct the request body
            const requestBody = {
                contents: [
                    {
                        parts: [{ text: prompt }]
                    }
                ]
            };

            try {
                // Make the API request
                const response = await fetch(apiUrl, {
                    method: "POST",
                    headers: {
                        "Content-Type": "application/json"
                    },
                    body: JSON.stringify(requestBody)
                });

                // Handle the response
                if (!response.ok) {
                    const errorText = await response.text();
                    throw new Error(`HTTP Error: ${response.status}\n${errorText}`);
                }

                const result = await response.json();

                
                // console.log(JSON.stringify(result, null, 2));
                // Extracting the text
                const text = result.candidates[0].content.parts[0].text;

                // Encoding the text to make it URL-safe
                const encodedText = encodeURIComponent(text);

                // Adding the text as a query parameter to the current URL
                const newUrl = `${window.location.pathname}?search=${encodedText}&keyword=${searchBar.value}`;

                // Redirecting to the new URL
                window.location.href = newUrl;
                //document.getElementById('response').innerText = JSON.stringify(result, null, 2);
            } catch (error) {
                console.log(error);
                //document.getElementById('response').innerText = `Error: ${error.message}`;
            }
        });
    </script>
</body>
</html>